### ISSUE TITLE
Compose button missing in recent Sanity releases

### ISSUE THREAD

**Issue by lauri865** [sanity-io/orderable-document-list#11]
I'm on version 2.23.2 on Sanity, and the compose button doesn't show up in the list anymore, works fine in some earlier versions. I think the breaking change came with v2.22.3 if I'm not mistaken.

**Comment by JonathanDoelan** [comment]
same here

**Comment by SimeonGriggs** [comment]
Can reproduce. Will investigate a fix. Thanks for reporting.

**Comment by SimeonGriggs** [comment]
Fixed in 0.0.4
