### ISSUE TITLE
Compatibility with custom preview

### ISSUE THREAD

**Issue by simonandywilson** [sanity-io/orderable-document-list#15]
Firstly, thanks for your work on this, it's really great.

I can't figure out if it's possible to use this plugin in conjunction with the `.views()` method in the desk structure builder. If a document is ordered with this plugin can it have a custom preview?

**Comment by SimeonGriggs** [comment]
Hey Simon!

It should work with `getDefaultDocumentNode` in Structure Builder, where you define the `views` for a schema type outside of the list of Structure Builder items.

https://www.sanity.io/docs/structure-builder-reference#97e44ce262c9
