### ISSUE TITLE
"Create new" action broken

### ISSUE THREAD

**Issue by doublejosh** [sanity-io/orderable-document-list#16]
After successful install and use, I noticed this plugin removes the normal create button and replaces it with an action menu item to create a new document... which doesn't work.

CONSOLE ERROR:
```
No handler defined for action: undefined
```

Is there something required in the config to set that?

I'm also not sure why the normal UI element is missing.

**UPDATE:** For clarity, we can still use the main create document button... just not the in-context create button.

**Comment by SimeonGriggs** [comment]
Oh! What version of the plugin and studio are you using?

**Comment by doublejosh** [comment]
Studio `2.10.0` ...looks like that's back a bit. But I have `0.0.4` of the plugin, which appears current.

**Comment by SimeonGriggs** [comment]
Believe this could be solved with a Studio upgrade. I can't recreate the issue on Studio `2.28.1` and plugin `0.0.4`.
