### ISSUE TITLE
Doesn't work with multiple ordered documents + styling isn't consistent with Studio

### ISSUE THREAD

**Issue by TomSmedley** [sanity-io/orderable-document-list#18]
https://www.loom.com/share/df94dce694004231b455c3defd82cbb0

I also found the clicking of the name a little confusing as it isn't consistent with the rest of the Studio, I wonder if you could click the drag handle rather than drag to achieve the same thing? I think that dragging multiple documents isn't used often enough to be the biggest click area.

May I suggest the following?
![List](https://user-images.githubusercontent.com/95056193/164546090-b79728a1-1df6-4a3b-8ce9-dd56e24bd2cc.jpg)

The hover state more consistent with the Array interface:
![List Hovered](https://user-images.githubusercontent.com/95056193/164546230-f8df94d7-b4cd-4275-b62b-1cea6e594d8c.jpg)

Then a user can click the handle to select (or drag to reorder):
![List Selected](https://user-images.githubusercontent.com/95056193/164546255-30d020da-28fa-4899-b131-b1b185d51e76.jpg)
- Click is detected by how much the mouse position has moved from mouse down to mouse up. If the mouse move becomes higher than a threshold it becomes a drag.

Clicking the name of the document now opens the document as expected:
![List Document Selected](https://user-images.githubusercontent.com/95056193/164546300-130257bc-55bc-4e65-b6bc-1407b0225faf.jpg)

**Comment by SimeonGriggs** [comment]
The arrow to open document has been removed in `0.0.6`

Thanks for the thoughtful and detailed feedback as well.

**Comment by TomSmedley** [comment]
Thanks @SimeonGriggs does it also fix the bug where switching between two draggable documents doesn't update the UI?

**Comment by SimeonGriggs** [comment]
Unfortunately not – that's something we need to follow up on the Studio side.

**Comment by SimeonGriggs** [comment]
@TomSmedley This is now solved in `0.0.8`
