### ISSUE TITLE
Problems with duplicating documents

### ISSUE THREAD

**Issue by nboliver** [sanity-io/orderable-document-list#19]
When trying to duplicate a document that is part of the orderable document list, sometimes the duplicate document gets "stuck" in an undefined state and won't publish: 

<img width="1192" alt="image" src="https://user-images.githubusercontent.com/3094055/164606567-cfb71022-a913-42a9-a361-8a3e3c57e7fe.png">

In the screenshot above, I just used the duplicate button and changed the slug. When I published, the list item swapped to the default icon and `Untitled`. A refresh of the page removes this duplicate, which is not the norm for Sanity, since you never have to save your work. 

There are no console errors, but there is a warning for the type I am using in the orderable list: 
<img width="503" alt="image" src="https://user-images.githubusercontent.com/3094055/164606864-2a101df6-719e-46e6-8c38-6942f081ba2c.png">

EDIT: 
Also having issues reordering documents. Here are some screenshots from network panel: 
<img width="760" alt="image" src="https://user-images.githubusercontent.com/3094055/164608363-77982fbf-ff6f-47c0-b158-cab13c914c9d.png">

<img width="888" alt="image" src="https://user-images.githubusercontent.com/3094055/164608427-da8c7fb9-bc82-4748-aae6-9b364c2ab166.png">

**Comment by SimeonGriggs** [comment]
`0.0.6` will highlight duplicated documents as they share the same `orderRank` value, unless you modify the built-in Duplicate Document Action.

Please update and let me know if your issue persists.

**Comment by nboliver** [comment]
Upgraded to 0.0.7 - the "untitled" document thing still persists but I'm not getting the reordering error anymore. 
<img width="528" alt="image" src="https://user-images.githubusercontent.com/3094055/166110397-7d689b94-6435-476e-a1f6-473884c2bd87.png">

**Comment by SimeonGriggs** [comment]
Are there any errors in your console? Any more info about your device/connection?

**Comment by nboliver** [comment]
Seems to be resolved now, may have been related to the other Sanity service issues that were happening around that time?
