### ISSUE TITLE
List not appearing when opening from an other orderable list

### ISSUE THREAD

**Issue by JonathanDoelan** [sanity-io/orderable-document-list#2]
Let’s say we have two schema-lists "list-a" and "list-b". Both of them are `orderable` by your plugin.

If list-a is opened (URL: …/desk/orderable-list-a) and I then open list-b (URL: …/desk/orderable-list-b) the column with the entries won’t update. 

It only works if I click on list-c (= not orderable) and after that on list-b.

**Comment by SimeonGriggs** [comment]
This is an issue in the Studio which we're looking to resolve.

**Comment by SimeonGriggs** [comment]
This should be resolved in Studio `2.21.8`

**Comment by mxseev** [comment]
@SimeonGriggs the bug is repeated on the new Sanity version.

```
@sanity/cli                      2.21.7 (up to date)
@sanity/base                     2.21.9 (up to date)
@sanity/cli                      2.21.7 (up to date)
@sanity/components               2.14.0 (up to date)
@sanity/core                     2.21.8 (up to date)
@sanity/default-layout           2.21.9 (up to date)
@sanity/default-login            2.21.9 (up to date)
@sanity/desk-tool                2.21.9 (up to date)
@sanity/form-builder             2.21.9 (up to date)
@sanity/orderable-document-list   0.0.3 (up to date)
@sanity/react-hooks              2.21.9 (up to date)
@sanity/vision                   2.21.9 (up to date)
```

**Comment by simrikservices** [comment]
Is this bug fixed ? I am still facing this issue and I am using `^2.29.5`.

**Comment by SimeonGriggs** [comment]
I was able to resolve this in the plugin, try upgrading to `0.0.8` 🎉
