### ISSUE TITLE
use plugin from sub-category

### ISSUE THREAD

**Issue by alexxlagutin** [sanity-io/orderable-document-list#20]
Hi Simeon!
First of all thank you for the plugin!
I have a little question, if you don't mind.

In my project I have a structure like Main Category -> Sub-category->Products
It is very similar to the one shown in this example https://www.sanity.io/docs/dynamically-group-list-items-with-a-groq-filter#ca61e2f7cd5e. 

Is this possible to use your plugin to order products placed this way?

Also I face an error even if I place `orderableDocumentListDeskItem` directly into the desk-structure/index.js
The error is: Error: Pane is missing router context
Everything is configured by the instructions.

What may be wrong?

**Comment by SimeonGriggs** [comment]
Currently the plugin can only create a specific ordering across **every** document of the same `_type`. So you cannot create filtered orderable lists.

However, if you had a single list to do all the ordering in, you could still use the exported `orderRankOrdering` to display your filtered lists in the same order.

---

As for your other issue with router context, are you on the latest version of the Studio?

**Comment by alexxlagutin** [comment]
Hi Simeon!
Thank you for your answer!

As for filtered orderable lists. Will this be possible in some observable future?

As for my second question - that was just some misconfiguration from my side. Now if works as expected!

**Comment by SimeonGriggs** [comment]
> Will this be possible in some observable future?

Anything's possible! :) but I can't say it will be 🔜 

> Now it works as expected!

🎉
