### ISSUE TITLE
Use `ORDER_FIELD_NAME` instead of hardcoding field name

### ISSUE THREAD

**Issue by sixclones** [sanity-io/orderable-document-list#23]
Hi,

[L50 of `src/DocumentListWrapper.js`](https://github.com/sanity-io/orderable-document-list/blob/main/src/DocumentListWrapper.js#L50) could use `ORDER_FIELD_NAME`.
```diff
<>
-  Schema <code>{type}</code> must have an <code>order</code> field of type{' '}
+  Schema <code>{type}</code> must have an <code>{ORDER_FIELD_NAME}</code> field of type{' '}
  <code>string</code>
</>
```

This will slightly improve DX :)

Thx,

Sixclones

**Comment by SimeonGriggs** [comment]
Good call. If you make a PR I'll merge it 😀

**Comment by SimeonGriggs** [comment]
Done in #30

**Comment by sixclones** [comment]
Sorry forgot to take the time to submit the PR. Thanks for adding it! 👍
