### ISSUE TITLE
Explain `orderings` in the schema. It's not clear.

### ISSUE THREAD

**Issue by surjithctly** [sanity-io/orderable-document-list#31]
In the docs, it says:

```
// Optional: The plugin also exports a set of 'orderings' for use in other Document Lists
  orderings: [orderRankOrdering],
```

But what does this code actually do? What if I did not add this? Please clarify this option as it's not understandable.

**Comment by SimeonGriggs** [comment]
Fair point, have added a link to https://www.sanity.io/docs/sort-orders above that line.
