### ISSUE TITLE
Publishing document 

### ISSUE THREAD

**Issue by thunder87** [sanity-io/orderable-document-list#37]
Publishing a document (updating it), changes the preview title to "Untitled".

![image](https://user-images.githubusercontent.com/13064503/186371421-95f49489-af51-4a09-9349-df7228476a9a.png)

Sanity: 2.30.5
Package version: 0.0.10

**Comment by SimeonGriggs** [comment]
Are you seeing this consistently? Like every single time you update a document?

**Comment by thunder87** [comment]
Sorry for the late response!
Yes, this is happening every time i publish.

**Comment by thunder87** [comment]
Sorry for the late response!
Yes, this is happening every time i publish.

**Comment by thunder87** [comment]
Hi! Any progress on this?

**Comment by SimeonGriggs** [comment]
I believe this is part of an underlying issue with the Studio which should hopefully be addressed soon.

**Comment by karltaylor** [comment]
Is there anyway to patch this functionality in the interim? @SimeonGriggs do you know what the underlying issue is?

**Comment by lotarbo** [comment]
I have the same problem
```
  @sanity/cli                      2.34.0 (up to date)
  @sanity/base                     2.34.0 (up to date)
  @sanity/core                     2.34.0 (up to date)
  @sanity/dashboard                2.34.0 (up to date)
  @sanity/default-layout           2.34.0 (up to date)
  @sanity/default-login            2.34.0 (up to date)
  @sanity/desk-tool                2.34.0 (up to date)
  @sanity/eslint-config-studio      2.0.0 (up to date)
  @sanity/orderable-document-list  0.0.10 (up to date)
  @sanity/vision                   2.34.0 (up to date)
```

**Comment by troymcginnis** [comment]
@SimeonGriggs Also currently experiencing this issue.
```
  @sanity/cli                      2.27.0 (up to date)
  @sanity/base                     2.27.2 (up to date)
  @sanity/core                     2.27.0 (up to date)
  @sanity/default-layout           2.27.2 (up to date)
  @sanity/default-login            2.27.0 (up to date)
  @sanity/desk-tool                2.27.2 (up to date)
```
