### ISSUE TITLE
Ordering is not applied in other lists

### ISSUE THREAD

**Issue by fabien** [sanity-io/orderable-document-list#4]
When I order my documents as such:

![image](https://user-images.githubusercontent.com/2749/137159076-f0990c8c-0ac4-405a-b1b1-20bb72dea979.png)

And then look at my documents from a plain list, the items are not ordered as expected:

![image](https://user-images.githubusercontent.com/2749/137159272-338bdca0-c67e-4943-8bbd-96f6aa0e955b.png)

**Comment by SimeonGriggs** [comment]
Please try `2.21.5` and report back if you still see the same.

**Comment by fabien** [comment]
Hi @SimeonGriggs - I just tried with `2.215` but the issue remains. Some lists reorder correctly, while others simply don't.

**Comment by SimeonGriggs** [comment]
Just an update, I can recreate the issue reliably and am looking into a fix.

**Comment by fabien** [comment]
Hi @SimeonGriggs - any updates on this? I just had another go at using your plugin but unfortunately, it's still not working as it should.

**Comment by SimeonGriggs** [comment]
This turned out to be a Studio-level issue, which I thought might've been addressed in a newer version. Were you using latest version of the Studio?

**Comment by fabien** [comment]
I'm running 2.27.1 right now, which is fairly recent, no? So what I noticed is that the ordering is applied correctly, and using it with GROQ works reliably. The orderable list views also display consistently.

However, the provided `orderRankOrdering` does not work as it should in other document listings. Whenever I choose this option from the menu as the sort order to use, it doesn't match the custom order I set. So if you ask me, the bug is actually in this part somehow.

**Comment by SimeonGriggs** [comment]
Yes it appears to be something in the Studio not respecting a custom ordering. Still under consideration.

**Comment by SimeonGriggs** [comment]
This should be resolved in Studio `2.30.0`

**Comment by fabien** [comment]
Hi Simeon, thanks for the update. I'm running the following setup:

@sanity/cli                      2.30.0 (up to date)
@sanity/base                     2.30.0 (up to date)
@sanity/code-input               2.30.0 (up to date)
@sanity/color-input              2.30.0 (up to date)
@sanity/components               2.14.0 (up to date)
@sanity/core                     2.30.0 (up to date)
@sanity/dashboard                2.30.0 (up to date)
@sanity/default-layout           2.30.0 (up to date)
@sanity/default-login            2.30.0 (up to date)
@sanity/desk-tool                2.30.0 (up to date)
@sanity/google-maps-input        2.30.0 (up to date)
@sanity/image-url                 1.0.1 (up to date)
@sanity/language-filter          2.29.8 (up to date)
@sanity/orderable-document-list   0.0.8 (up to date)
@sanity/production-preview       2.29.3 (up to date)
@sanity/vision                   2.30.0 (up to date)

For some reason, it's still not working when I check back with 'Sort by Ordered' in my main document list. Odd, no?
