### ISSUE TITLE
Unable to find draggable with id: c4f95001-5f56-41c7-9712-2ce23dd4270a

### ISSUE THREAD

**Issue by ElektrikSpark** [sanity-io/orderable-document-list#44]
Hi! I am trying to implement the latest version of orderable-document-list in [nextjs-blog-cms-sanity-v3](https://github.com/sanity-io/nextjs-blog-cms-sanity-v3).

I have it set up, but I am unable to drag the items.

react-beautiful-dnd: `Unable to find draggable with id: c4f95001-5f56-41c7-9712-2ce23dd4270a`

I am also getting a warning, `Warning: Connect(Droppable): Support for defaultProps will be removed from memo components in a future major release. Use JavaScript default parameters instead.`

I will keep playing around, but is there a working repo of this plugin working in Sanity Studio v3? An example would go a long way.

Thanks! ❤️

**Comment by kaanbasal** [comment]
@ElektrikSpark its related to `react-beautiful-dnd` package that is used causing the issue. you can see the details here:

https://github.com/atlassian/react-beautiful-dnd/issues/2350

**Comment by ElektrikSpark** [comment]
Can anyone confirm that they have Sanity Studio v3 working with this plugin (able to drag items)?

**Comment by ElektrikSpark** [comment]
I was finally able to try the studio in production, and it seems that everything is working! I guess this plugin does not currently work in development?

**Comment by alainkaiser** [comment]
@ElektrikSpark I got the exact same issue as you described above. Also on my end, the drag and drop functionality of the plugin only works in production.

The warning i am getting is the following one:

`Warning: Connect(Droppable): Support for defaultProps will be removed from memo components in a future major release. Use JavaScript default parameters instead.`

In production, the plugin works perfectly. Any plans on how we could resolve it in dev?

**Comment by alainkaiser** [comment]
Opened a PR for this one.
