### ISSUE TITLE
Type '{ title: string; name: string; by: { field: "orderRank"; direction: string; }[]; }' is not assignable to type 'SortOrdering'.

### ISSUE THREAD

**Issue by ElektrikSpark** [sanity-io/orderable-document-list#46]
`import { orderRankField, orderRankOrdering } from '@sanity/orderable-document-list';`

`orderings: [orderRankOrdering],`

`Types of property 'by' are incompatible.
    Type '{ field: "orderRank"; direction: string; }[]' is not assignable to type 'SortOrderingItem[]'.
      Type '{ field: "orderRank"; direction: string; }' is not assignable to type 'SortOrderingItem'.
        Types of property 'direction' are incompatible.
          Type 'string' is not assignable to type '"asc" | "desc"'.`

Using `"@sanity/orderable-document-list": "^1.0.1"`

**Comment by SimeonGriggs** [comment]
Should be fixed in #58
