### ISSUE TITLE
the V3 version Guide is so confusing and unclear. 

### ISSUE THREAD

**Issue by AbdellahSlimani** [sanity-io/orderable-document-list#49]
I used the v2 version before and it was pretty much easy to add to any of my projects. but now when I try to use the v3, the guide and steps are just so confusing. please put in mind that sanity is not that famous and it's plugins are not very widely used. and trying to find another guide or tutorial is not possible. so please be more clear. or if you can add a video explanation

**Comment by feledori** [comment]
Hey I think your wording is a bit off and you probably don't mean it like you wrote it. But what is unclear to you? Which step? Just saying it doesn't fit your style of understanding or idk what isn't very helpful.

**Comment by seamofreality** [comment]
As a first time user of this plugin and no former usage in v2 I can say that, for me, looking at section "2. Add the orderRank field to your schema(s)." got me a bit puzzled. 

> You must pass in the type of the schema and the schema context, to create an initialValue value. Context is available in the schema callback, and should be forwarded as is.

From the example I assume it means "to pass in the type and the context to `orderableDocumentListDeskItem()` within in the structure property of the deskTool", but then I think it would be better suited to section 1 and seems obsolete here?

And in the example, there's no import for `orderRankField()` or `orderRankOrdering()`, so I was like "okay, where's that coming from?"

So far it all works, so I guess I'm not too far off reading the documentation correctly. 
Hope the feedback helpes on the matter, tho :)

**Comment by SimeonGriggs** [comment]
Thanks for your feedback.

The functions imported into schema were incorrectly documented, it has been fixed in #54
