### ISSUE TITLE
Post id

### ISSUE THREAD

**Issue by uzproblue** [sanity-io/orderable-document-list#53]
Is there any way to change these values to numbers [1,2,3...]

![task1](https://user-images.githubusercontent.com/48709598/212347003-db92cda8-2f14-4d83-8ea1-d3e9a42371f8.png)

**Comment by SimeonGriggs** [comment]
Not possible, the plugin uses these strings so that it can create a new value between two existing values without needing to update all others.

If it used numbers, the plugin could potentially need to write a change to every other document.
