### ISSUE TITLE
Open document is not highlighted in the list

### ISSUE THREAD

**Issue by ndimatteo** [sanity-io/orderable-document-list#59]
When you click a document from the orderable list it doesn't apply the active state to the opened opened document in the list:
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/737188/228651820-f3851f3a-dcb9-4b38-992b-acd942eee5d4.png">

**Comment by toddpadwick** [comment]
I experience this too. and its really confusing when you have loads of documents. 
I also noticed the hover highlight looks a bit broken with a white square around the text:
![Screenshot 2023-06-14 at 12 11 11](https://github.com/sanity-io/orderable-document-list/assets/36191462/24acef19-50ff-493f-b835-66745ae3d673)
