### ISSUE TITLE
Reset Order does nothing (at times)

### ISSUE THREAD

**Issue by fabien** [sanity-io/orderable-document-list#6]
I have a list of documents that have not been assigned an order ranking yet. Choosing it from the top right menu does nothing. Again, intermittently, as it has been working on other occasions for me.

Locally, it only works once, just after reloading the app completely (full browser window reload). After that, none of the other lists are able to reset the order. I have multiple lists/types without such orders right now.

**Comment by SimeonGriggs** [comment]
I'm able to recreate the issue, but only intermittently as you say. Will investigate. Thanks for reporting!

**Comment by SimeonGriggs** [comment]
This appears to be resolved in Studio version `2.21.8`
