### ISSUE TITLE
Label and preview fails to render when published changes are made

### ISSUE THREAD

**Issue by toddpadwick** [sanity-io/orderable-document-list#63]
When publishing changes, the preview 'says' untitled, which gives the impression that data is lost - which can be very worrying for the content manager. Our clients have panicked over this multiple times.

The below screenshot shows a document that has been published for a while, but i simply made a copy change and published the update. However, the preview on the left, shows 'untitled'.
![Screenshot 2023-06-14 at 12 07 13](https://github.com/sanity-io/orderable-document-list/assets/36191462/2edb555a-d869-419f-b167-a85311b5f60e)

**Comment by tomaszter** [comment]
Same issue here with Sanity v3.12.1
