### ISSUE TITLE
deskTool is deprecated

### ISSUE THREAD

**Issue by darronz** [sanity-io/orderable-document-list#84]
**Is your feature request related to a problem? Please describe.**
After v3.20.0 [Desk is now Structure](https://www.sanity.io/help/desk-is-now-structure)

**Describe the solution you'd like**
The readme in this project describes installation as 
```javascript
import { deskTool, StructureBuilder } from 'sanity/structure'

export default defineConfig({
  //...
  plugins: [
    deskTool({
      structure: (S, context) => {
```

**Describe alternatives you've considered**
This should be updated to
```javascript
import { structureTool } from 'sanity/structure'

export default defineConfig({
  //...
  plugins: [
    structureTool({
      structure: (S, context) => {
```

**Comment by SimeonGriggs** [comment]
Fixed in #99
